#!/bin/sh

set -x

rm -rf CMakeFiles CMakeCache.txt lib/CMakeFiles prog/CMakeFiles Makefile */Makefile
rm -rf build.ninja	libtodo.a	rules.ninja
# rm -rf Makefile.in
rm -rf aclocal.m4
# rm -rf configure
rm -rf config.status
rm -rf config.log
rm -rf libtool
rm -rf libtodo.a
rm -rf */*.o
# rm -rf config
rm -rf autom4te.cache
rm -rf cmake_install.cmake
rm -rf */cmake_install.cmake
rm -rf .dirstamp */.dirstamp
rm -rf .deps */.deps
rm -rf .lib/libtodostatic.a
rm -rf ./lib/libtodoshared.dylib
rm -rf ./lib/libtodostatic.a
rm -rf todo
